UI: make normal copy and paste operator singular
The operators used to copy normals can only be used on a single
element, otherwise the following error appears:

> Error: Can only copy one custom normal, vertex normal or face normal

It should be made clear in the UI by making "Vector" singular, so that
"Copy Vectors" is replaced by "Copy Vector", and
"Paste Vectors" is replaced by "Paste Vector".