Fix: error when selecting Size Mode in Import Images as Planes
When importing images as planes, on Size Mode update, this error would
be raised in the console because the update tried to assign a value to
a nonexistant member of the class:

```
Traceback (most recent call last):
  File "scripts/startup/bl_operators/image_as_planes.py", line 507, in update_size_mode
    self._prev_align_axis = 'NONE'
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'IMAGE_OT_import_as_mesh_planes' object has no attribute '_prev_align_axis'
File "scripts/startup/bl_operators/image_as_planes.py", line 498, in update_size_mode
```