Fix error installing an addon by drag'n'drop after fcba8b8099
The error was

Error: Python: Traceback (most recent call last):
  File "\blender-4.2.0-beta+v42.4e4d8476c49f-windows.amd64-release\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2145, in invoke
    return self._invoke_for_drop(context, event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\blender-4.2.0-beta+v42.4e4d8476c49f-windows.amd64-release\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2206, in _invoke_for_drop
    if not self._repos_valid_for_install():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EXTENSIONS_OT_package_install_files._repos_valid_for_install() missing 1 required positional argument: 'context'